site_name: AI-Based Audio Mixing and Mastering
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - Data Handling: data.md
  - Usage: usage.md
  - Notebooks: notebooks.md
  - Inference: inference.md
  - API Reference: api_reference.md
  - Contribution Guidelines: contributing.md
  - Continuous Integration: ci_cd.md
  - Changelog: changelog.md
